name 'userAdministration'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures userAdministration'
long_description 'Installs/Configures userAdministration'
version '0.1.0'
